version: "3"
services:

  mysql8:
    image: mysql:8.0.25
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本
#      - ./script/mysql/user.sql:docker-entrypoint-initdb.d
      - D:\go\GO-LEARNING\src\webook\script\mysql:/docker-entrypoint-initdb.d
    ports:
      # 映射 13316端口
      - "13316:3306"
